name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add your build and test steps here

      - name: Run test suite
        run: |
          # Add commands to execute the test suite

      # Add more steps as needed

      - name: Build and test
        run: |
          # Add commands to build and test the project
- name: Veracode Dependency Scanning
        uses: veracode/veracode-sca@v2.1.10
            
