name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add your build and test steps here

      - name: Fix failing step
        run: |
          # Add the necessary commands to fix the failing step

      # Add more steps as needed

      - name: Veracode Dependency Scanning
        with:
          api_id: ${{ secrets.VERACODE_API_ID }}
          api_key: ${{ secrets.VERACODE_API_KEY }}
          fileinclude: **/*.js
          direxclude: 
          verbose: false
          teamid: ${{ secrets.VERACODE_TEAM_ID }}
        uses: veracode/veracode-sca@v2.1.10
            
