name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        uses: docker://postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y <dependencies>

      - name: Build TimescaleDB
        run: |
          cd timescaledb
          cmake -DCMAKE_BUILD_TYPE=Debug .
          make
          cd ..

      - name: Run tests
        run: |
          cd timescaledb/build
          make installcheck
